// Drawing → G-code for this plotter's firmware (GRBL subset, pen on M3/M5).

import { Drawing } from "./types";

/**
 * Header comment stamped on every program this generator emits. It marks a file
 * as "ours" — a single `G1 F<feed>` header followed by feed-less `G1 X Y` draw
 * moves — so tools can safely rewrite its draw feed. Authored G-code lacks it.
 */
export const GENERATED_MARKER = "; generated by plotter-utils";

export interface GcodeGenerateOptions {
  /** Drawing feedrate in mm/min (G1). Defaults to the firmware default max. */
  feedMmMin?: number;
  /** Dwell after pen-down so the servo settles before drawing, in ms. */
  penSettleMs?: number;
  /** Return to origin and release the motors at the end. */
  finishAtOrigin?: boolean;
}

function formatCoord(value: number): string {
  return Number(value.toFixed(3)).toString();
}

/**
 * Emit a complete G-code program that draws the polylines in order.
 * Travel moves are G0 rapids with the pen up; strokes are G1 at `feedMmMin`.
 */
export function drawingToGcode(drawing: Drawing, options: GcodeGenerateOptions = {}): string {
  const feed = options.feedMmMin ?? 1500;
  const settleMs = options.penSettleMs ?? 100;
  const finishAtOrigin = options.finishAtOrigin ?? true;

  const lines: string[] = [
    GENERATED_MARKER,
    "G21 ; mm",
    "G90 ; absolute",
    "M5 ; pen up",
    `G1 F${formatCoord(feed)}`,
  ];

  for (const polyline of drawing.polylines) {
    if (polyline.length < 2) continue;
    lines.push(`G0 X${formatCoord(polyline[0].x)} Y${formatCoord(polyline[0].y)}`);
    lines.push("M3 ; pen down");
    if (settleMs > 0) lines.push(`G4 P${Math.round(settleMs)}`);
    for (let index = 1; index < polyline.length; index++) {
      lines.push(`G1 X${formatCoord(polyline[index].x)} Y${formatCoord(polyline[index].y)}`);
    }
    lines.push("M5 ; pen up");
  }

  if (finishAtOrigin) lines.push("G0 X0 Y0");
  return lines.join("\n") + "\n";
}

/**
 * Rewrite the draw (pen-down) feedrate of a program this generator produced, so
 * an already-generated file runs at a new speed without re-running the whole
 * pipeline. Used to refeed queued jobs to the board's tuned max feed after it
 * is retuned.
 *
 * Only touches gcode carrying `GENERATED_MARKER` — where the draw feed is a
 * single `G1 F<feed>` header and every draw move is a feed-less `G1 X Y`, so
 * rewriting that one line changes the whole drawing's speed exactly. Authored
 * G-code (which may set its own per-move feeds) is left untouched.
 *
 * @param gcode      An existing G-code program.
 * @param feedMmMin  New pen-down feedrate in mm/min.
 * @returns The rewritten program, or null if `gcode` isn't our generated format
 *          (so callers can skip files they don't own).
 */
export function retargetDrawFeed(gcode: string, feedMmMin: number): string | null {
  if (!gcode.includes(GENERATED_MARKER)) return null;
  let rewrites = 0;
  // Anchor to a full line so `G1 X.. Y..` draw moves (no F word) never match.
  const rewritten = gcode.replace(/^G1 F-?\d*\.?\d+([^\S\n]*(?:;.*)?)$/gm, (_match, trailing) => {
    rewrites++;
    return `G1 F${formatCoord(feedMmMin)}${trailing}`;
  });
  return rewrites > 0 ? rewritten : null;
}
